### ISSUE TITLE
marionette resolve issue with webpack 2 build

### ISSUE THREAD

**Issue by fxmaxvl** [AndrewHenderson/marionette-redux#1] opened 2017-03-01 17:35 UTC
if I trying import your module as es6 module, then error happens:
ERROR in ../~/marionette-redux/dist/marionette-redux.js
Module not found: Error: Can't resolve 'marionette' in '.../node_modules/marionette-redux/dist'

I think trouble in that line: 
https://github.com/AndrewHenderson/marionette-redux/blob/master/dist/marionette-redux.js#L10

>>> require("marionette")
---
maybe need use require('backbone.marionette')?

**Comment by AndrewHenderson** [comment] 2017-03-01 19:30
That's the build meant for UMD. I'll look into this. I'm assuming it's due to a misconfig in the package.json and that npm needs to point to either the [source root file](https://github.com/AndrewHenderson/marionette-redux/blob/master/src/marionette-redux.js) or an es build.

**Comment by fxmaxvl** [comment] 2017-03-02 08:24
I tried yet another case that works for me -
just extend my webpack.config with new alias))
```
resolve: {
    alias: {
        marionette: 'backbone.marionette'   
    }
}
``` 

but i think - need create more stable solution for that. because your module, It seem to me, would be very useful for anyone, who wants to try redux with marionette, or searches (like me) painless ways to migrate marionette app into redux/react stack

**Comment by AndrewHenderson** [comment] 2017-03-02 18:36
Glad to hear you were able to get it working! I'll work on resolving this issue.

I appreciate the support. It's nice to know developers are finding the module useful.

I'd be very interested to learn about your migration effort. As well as how this modules serves you while you migrate from Marionette to React.

I currently work at an organization that has a very complex Marionette application. We continue to discuss migration. However, there fear of feature regression is currently deterrent.

**Comment by AndrewHenderson** [comment] 2018-01-24 07:23
@fxmaxvl I believe this is resolved by https://github.com/AndrewHenderson/marionette-redux/pull/2

**Closed as completed by AndrewHenderson** 2018-01-24 07:23 UTC
